# Generated by Django 4.1.13 on 2026-03-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_avatars/'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public groups are discoverable and joinable without invite.'),
        ),
        migrations.AddField(
            model_name='room',
            name='join_approval_required',
            field=models.BooleanField(default=False, help_text='Require admin approval for join requests.'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_members',
            field=models.PositiveIntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='room',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='slow_mode_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Minimum delay between messages per member (0=off).'),
        ),
        migrations.AddField(
            model_name='room',
            name='username',
            field=models.CharField(blank=True, help_text='Public group @username for search/join.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('direct', 'Direct'), ('group', 'Group')], db_index=True, default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
