# Generated by Django 4.1.13 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_room_avatar_room_description_room_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="avatar_crop_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="avatar_crop_width",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="avatar_crop_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="avatar_crop_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
