# Generated by Django 4.1.13 on 2026-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_avatar_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
        migrations.AddField(
            model_name='room',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, help_text='Negative 10-digit public fallback id for groups.', max_length=11, null=True, unique=True),
        ),
    ]
