# Generated by Django 4.1.13 on 2026-03-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_username_room_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, help_text='Negative 10-digit public fallback id for groups.', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='public_id must be a negative 10-digit numeric value.', regex='^-[1-9]\\d{9}$')]),
        ),
    ]
