# Generated by Django 4.1.13 on 2026-03-22 00:55

from django.db import migrations, models
import users.avatar_service


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.avatar_service.group_avatar_upload_to),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'public')), fields=('kind',), name='room_single_public_kind_uniq'),
        ),
    ]
