[pytest]
DJANGO_SETTINGS_MODULE = chat_app_django.settings
python_files = test_*.py
testpaths =
    .
norecursedirs =
    .venv
    venv
    node_modules
    .pytest_cache
    tmp_test_media
    tmp_test_temp
addopts = -ra
