[pytest]
DJANGO_SETTINGS_MODULE = chat_app_django.settings
python_files = test_*.py
testpaths =
    auditlog/tests
    chat/tests
    chat_app_django/tests
    users/tests
norecursedirs =
    .venv
    venv
    node_modules
addopts = -ra
