# Generated by Django 4.1.13 on 2026-03-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0002_message_room_fk'),
        ('rooms', '0002_room_avatar_room_description_room_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Admin label for this invite link.', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means the link never expires.', null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 means unlimited uses.')),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_links', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='rooms.room')),
            ],
            options={
                'db_table': 'groups_invite_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='chat_messages.message')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_messages', to='rooms.room')),
            ],
            options={
                'db_table': 'groups_pinned_message',
                'ordering': ['-pinned_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message from the user requesting to join.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invite_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='groups.invitelink')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_join_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pinnedmessage',
            constraint=models.UniqueConstraint(fields=('room', 'message'), name='pin_room_message_uniq'),
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['room', 'status'], name='joinreq_room_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('room', 'user'), name='one_pending_request_per_user'),
        ),
        migrations.AddIndex(
            model_name='invitelink',
            index=models.Index(fields=['room', 'is_revoked'], name='invite_room_revoked_idx'),
        ),
    ]
