# Generated by Django 4.1.13 on 2026-04-03 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_slug_alter_room_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_messages', '0004_message_read_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.CreateModel(
            name='MessageAttachmentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('received_bytes', models.PositiveBigIntegerField(default=0)),
                ('storage_name', models.CharField(max_length=500, unique=True)),
                ('chunk_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('complete', 'Complete')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_uploads', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachment_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_attachment_upload',
            },
        ),
        migrations.AddIndex(
            model_name='messageattachmentupload',
            index=models.Index(fields=['user', 'room', 'status'], name='att_upl_user_room_st_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachmentupload',
            index=models.Index(fields=['expires_at'], name='attachment_upload_exp_idx'),
        ),
    ]
