# Generated by Django 4.1.13 on 2026-03-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('protocol', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('actor_user_id_snapshot', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('actor_username_snapshot', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('method', models.CharField(blank=True, max_length=16, null=True)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('ip', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['created_at', 'id'], name='audit_evt_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_user_id_snapshot', 'created_at'], name='audit_evt_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'created_at'], name='audit_evt_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['protocol', 'created_at'], name='audit_evt_proto_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['status_code', 'created_at'], name='audit_evt_status_created_idx'),
        ),
    ]
