# Generated by Django 4.1.13 on 2026-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_chatrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Per-room display name (like Discord server nickname).', max_length=32),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If True, this is the @everyone role (auto-applied to all members).'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.BigIntegerField(default=0, help_text='Bitwise permission mask (see roles.permissions.Perm).'),
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Higher position = more authority. Used to resolve hierarchy.'),
        ),
    ]
