# Generated by Django 4.1.13 on 2026-03-07 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0004_alter_membership_nickname_alter_role_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='muted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutes_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='muted_until',
            field=models.DateTimeField(blank=True, help_text='Muted until this time (null = not muted).', null=True),
        ),
    ]
