# Generated by Django 4.1.13 on 2026-03-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentitycore',
            name='public_id',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='public_id must be a positive 10-digit numeric value.', regex='^[1-9]\\d{9}$')]),
        ),
    ]
