# Generated by Django 4.1.13 on 2026-03-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_useridentitycore_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthidentity',
            name='avatar_url_from_provider',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
