# Generated by Django 4.1.13 on 2026-03-19

from django.db import migrations, models

import users.avatar_service


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_widen_avatar_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="avatars/Password_defualt.jpg",
                upload_to=users.avatar_service.profile_avatar_upload_to,
            ),
        ),
    ]
